choche/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'app.views.index', name='home'),
    url(r'^disponibilidad/$', 'app.views.disponibilidad', name='disponibilidad'),
    url(r'^datos_personales/(?P<pk>\d+)/$', 'app.views.datos_personales', name='datos_personales'),
    url(r'recibo/(?P<pk>\d+)/$', 'app.views.recibo', name='recibo'),
    url(r'^administrador/', include('joseadmin.urls', namespace='administrador'), ),

]

joseadmin/urls.py
__author__ = 'mrk2'
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import ReservacionList, ClientesList, PaqueteList, PaqueteCreation,\
    PaqueteUpdate,PaqueteDelete, ReservacionUpdate

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^$', 'app.views.index', name='home'),
    url(r'^reservaciones/$', ReservacionList.as_view(), name='reservaciones'),
    url(r'^clientes/$', ClientesList.as_view(), name='clientes'),
    url(r'^paquete/$', PaqueteList.as_view(), name='paquetes'),


    # crud paquete
    url(r'^nuevo_paquete$', PaqueteCreation.as_view(), name='paqueteNew'),
    url(r'^editar_paquete/(?P<pk>\d+)$', PaqueteUpdate.as_view(), name='paqueteEdit'),
    url(r'^eliminar_paquete/(?P<pk>\d+)$', PaqueteDelete.as_view(), name='paqueteDelete'),

    # crud reservacion
    url(r'^editar_confirmacion/(?P<pk>\d+)$', ReservacionUpdate.as_view(), name='reservacionEdit'),



]

app/models.py
from django.db import models

# Create your models here.


class Paquete(models.Model):
    nombre = models.CharField(max_length=20)
    personas = models.CharField(max_length=3)
    sillas = models.SmallIntegerField()
    cubresillas = models.SmallIntegerField("cubre sillas", null=True, blank=True)
    mesas = models.SmallIntegerField()
    manteles = models.SmallIntegerField()
    cubremanteles = models.SmallIntegerField()
    juego_loza = models.SmallIntegerField("Juegos de loza, vaso, plato, cubiertos", blank=True, null=True)
    precio = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=120)
    ciudad = models.CharField(max_length=150)
    direccion = models.TextField()
    codigo_postal = models.SmallIntegerField()
    telefono = models.IntegerField()
    email = models.EmailField()
    c_email = models.EmailField("Confirmar e-mail", )
    tyc = models.BooleanField("Terminos y condiciones",)

    def __str__(self):
        return self.nombre

class Reservacion(models.Model):
    paquete = models.ForeignKey(Paquete)
    cliente = models.ForeignKey(Cliente)
    fecha_ahora = models.DateField(auto_now_add=True)
    fecha = models.DateField(unique=True)
    confirmacion = models.BooleanField()

    def __str__(self):
        return "%s, %s"% (self.paquete, self.cliente)

joseadmin/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from .models import Cliente
from django.forms import Form


class DisponibiliddadForm(forms.Form):
    fecha = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('nombre', 'apellidos', 'ciudad', 'direccion', 'codigo_postal', 'telefono', 'email', 'c_email', 'tyc',)

        widgets = {
            'nombre': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'ciudad': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'codigo_postal': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'email': forms.TextInput(attrs={'type': 'email', 'class': 'form-control'}),
            'c_email': forms.TextInput(attrs={'type': 'email', 'class': 'form-control'}),
            'tyc': forms.TextInput(attrs={'type': 'checkbox', 'class': 'form-control'}),
        }

app/views.py
from django.shortcuts import render, redirect
from .models import Paquete, Reservacion, Cliente
from .forms import DisponibiliddadForm, ClienteForm
from django.utils.dateparse import parse_date
from datetime import timedelta,datetime

# Create your views here.

def index(request):
    return render(request, 'index.html')

def disponibilidad(request):
    form = DisponibiliddadForm()
    if request.method == 'POST':
        form = DisponibiliddadForm(request.POST)
        if form.is_valid():
            fecha = form.cleaned_data['fecha']
            print(fecha)
            if Reservacion.objects.filter(fecha=fecha).exists():
                reservacion = Reservacion.objects.get(fecha=fecha)
                res = reservacion.fecha_ahora
                resPropuesta = reservacion.fecha
                dias3= timedelta(days=3)
                total = res + dias3
                context = {
                       'fecha': fecha,
                        'form': form,
                        'dia3':total,
                        'resPropuesta':resPropuesta,
                }
                return render(request, 'disponibilidad.html', context)
            else:
                paquetes = Paquete.objects.all().order_by('nombre')
                context = {
                    'fecha': fecha,
                    'paquetes': paquetes,
                    'form': form,
                }
                return render(request, 'disponibilidad.html', context)

    paquetes = Paquete.objects.all().order_by('nombre')
    context = {
        'paquetes': paquetes,
        'form': form,
    }
    return render(request, 'disponibilidad.html', context)

def datos_personales(request, pk):
    paquete = Paquete.objects.get(id=pk)
    form =  ClienteForm()
    if request.method == 'POST':
        if 'datos-personales' in request.POST:
            form =  ClienteForm(request.POST)
            paquet = request.POST.get('paquete', False)
            fecha = request.POST.get('fecha', False)
            if form.is_valid():
                form.save()
                ultimoUsuario = Cliente.objects.last()
                obtenerPaquete = Paquete.objects.get(id=paquet)
                nuevareserva = Reservacion(paquete=obtenerPaquete,cliente=ultimoUsuario, fecha=fecha)
                nuevareserva.save()
                ultimopk = Reservacion.objects.last()
                idpk = ultimopk.id
                return redirect('recibo', pk=idpk)

        if 'fecha-entrega' in request.POST:
            fecha = request.POST.get('fecha', False)
            context = {
                'fecha': fecha,
                'form': form,
                'paquete': paquete,
            }
            return render(request, 'datos_personales.html', context)

    context = {
        'form': form,
        'paquete': paquete,
    }
    return render(request, 'datos_personales.html', context)

def recibo(request, pk):
    ultimo = Reservacion.objects.get(pk=pk)
    return render(request, 'recibo.html', {'ultimo':ultimo})

joseadmin/views.py
from django.shortcuts import render
from app.models import *
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

# Create your views here.

class ReservacionList(ListView):
    model = Reservacion
    template_name = 'reservaciones-admin.html'

class ReservacionUpdate(UpdateView):
    model = Reservacion
    template_name = "reservaciones/actualizar-reservacion.html"
    fields = ['confirmacion']
    success_url = reverse_lazy('administrador:reservaciones')


class ClientesList(ListView):
    model = Cliente
    template_name = 'clientes-admin.html'

class PaqueteList(ListView):
    model = Paquete
    template_name = 'paquete-admin.html'

class PaqueteCreation(CreateView):
    model = Paquete
    template_name = "paquetes/crear_paquete.html"
    success_url = reverse_lazy('administrador:paquetes')
    fields = ['nombre', 'personas', 'sillas', 'cubresillas', 'mesas', 'manteles', 'cubremanteles', 'juego_loza', 'precio']

class PaqueteUpdate(UpdateView):
    model = Paquete
    template_name = 'paquetes/actualizar_paquete.html'
    success_url = reverse_lazy('administrador:paquetes')
    fields = ['nombre', 'personas', 'sillas', 'cubresillas', 'mesas', 'manteles', 'cubremanteles', 'juego_loza', 'precio']


class PaqueteDelete(DeleteView):
    model = DeleteView
    success_url = reverse_lazy('administrador:paquetes')

app/templates/datos_personales.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>PAGINA PRINCIPAL SALÓN FUENTES</title>







<!-- Bootstrap core CSS -->
<link href="{%  static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{%  static "css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet" media="screen">
   <script type="text/javascript" language="javascript" src="{%  static "js/jquery.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{%  static "js/jquery.dataTables.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{%  static "js/bootstrap.min.js"%}"></script>
    <script type="text/javascript" language="javascript" src="{%  static "js/bootstrap-modal.js"%}"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('.toggle-modal').click(function(){
		$('#logout').modal('toggle');
	});
});
</script>

<!-- Custom styles for this template -->

<link href="{%  static "css/offcanvas.css" %}" rel="stylesheet">
<link rel="stylesheet" href="{%  static "css/prettyPhoto/css/prettyPhoto.css" %}" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
 <link href="{%  static "css/facebox/facebox.css" %}" media="screen" rel="stylesheet"  type="text/css" />
</head>

<body>
<!--Header-->
	    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="/">PAGINA PRINCIPAL SALÓN FUENTES</a>
	        </div>
	        <div class="collapse navbar-collapse">
	          <ul class="nav navbar-nav">



	          </ul>
	        </div><!-- /.nav-collapse -->
	      </div><!-- /.container -->
	    </div><!-- /.navbar -->

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="well">

				<!-- <img  width="1100px" hieght="100px" class="img-rounded"/> -->
					<div class="media">
					  <a class="pull-left" href="#">
					    <img class="media-object" src="{%  static "img/banner1.png" %}" alt="...">
					  </a>
					</div>
				</div>
			</div>
		</div>
	</div>


<!--End of Header-->
<div class="container">
<!--End of Header-->
<div class="container">

<!--Side bar-->
			<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
			<div class="sidebar-nav">
		   <div class="panel panel-primary">

			 <div class="panel-heading">Reservaciones</div>
               <div class="panel-body">
						   <form  method="POST">
                                {% csrf_token %}
								<div class="col-xs-12 col-sm-12">
					            	<div class="form-group">
					            		<div class="row">
					            			<div class="col-xs-12 col-sm-12">
					            				<label class="control-label" for="from">Disponibilidad </label>
                                                    {{ form.fecha }}
						              		</div>
						            	</div>
						            </div>
						            <div class="form-group">
						            	<div class="row">
					            			<div class="col-xs-12 col-sm-12">
						           				 <button type="submit" class="btn btn-primary" align="right"name="avail">Checar Disponibilidad</button>
						           			 </div>
						            	</div>
						            </div>
						        </div>
					        </form>
						</div>
		</div>
		    <hr>
	</div>
			<!--/.well -->
		</div>
		<!--/span-->
		<!--End of Side bar-->

		<div class="col-xs-12 col-sm-9">
			<!--<div class="jumbotron">-->
				<div class="">
					<div class="panel panel-default">
						<div class="panel-body">
							<fieldset>
								<p class="bg-warning">
									<div class="alert alert-info" >Fecha de reservación:      {{ fecha }}<strong></strong>  </div></p>
								<legend><h2 class="text-left">Eventos</h2></legend>

							</fieldset>
                             <table class="table table-hover">
                    <thead>
                      <tr bgcolor="#999999">
                      <th width="10">Tipo paquete</th>
                      <th align="center" width="120">personas</th>
                      <th align="center" width="120">sillas</th>
                      <th align="center" width="120">cubresillas</th>
                      <th align="center" width="120">mesas</th>
                      <th width="120">manteles</th>
                      <th align="center" width="120">cubre-manteles</th>
                      <th align="center" width="90">juego loza</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>{{ paquete.nombre }}</td>
                            <td>{{ paquete.personas }}</td>
                            <td>{{ paquete.sillas }}</td>
                            <td>{{ paquete.cubresillas }}</td>
                            <td>{{ paquete.mesas }}</td>
                            <td>{{ paquete.manteles }}</td>
                            <td>{{ paquete.cubremanteles }}</td>
                            <td>{{ paquete.juego_loza }}</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6"></td>
                            <td align="right"><h5><b>Total:  </b></h5></td>
                            <td align="left"><h5><b> {{ paquete.precio }}</b></h5></td>
                        </tr>
                        <tr>
                        </tr>
                    </tfoot>
                    </table>
                            <form action="" method="post">
                                {% csrf_token %}


                                {{ form }}
                                <hr/>
                                <input type="hidden" value="{{ paquete.id }}" name="paquete"/>
                                <input type="hidden" value="{{ fecha }}" name="fecha"/>
                                <input type="submit" class="btn btn-danger" name="datos-personales"/>
                            </form>



						</div>
					</div>
				</div>
		<!--	</div>-->
		</div>
		<!--/span-->
		<!--Sidebar-->

	</div>
	<!--/row-->
	<!--/row-->

	<hr>
	     <footer>

		 <script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.js" %}" charset="UTF-8"></script>
		 <script type="text/javascript" src="{%  static "js/locales/bootstrap-datetimepicker.uk.js" %}" charset="UTF-8"></script>


    <script type="text/javascript">
	// The facebox Jquery
	 $(document).ready(function($) {
	  $('a[rel*=facebox]').facebox({
	        loadingImage : 'images/facebox/loading.gif',
	        closeImage   : 'images/facebox/closelabel.png'
	           })
	  });

	  //The slideshow Jquery
	$(document).ready( function(){
		$('#slideshowHolder').jqFancyTransitions({ width: 477, height: 215 });
	});

	//The light box Jquery
				$(document).ready(function(){
					$("area[rel^='prettyPhoto']").prettyPhoto();

					$(".lightbox:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: true});
					$(".lightbox:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:10000, hideflash: true});
				});
	</script>
    <script type="text/javascript">
	$('.from').datetimepicker({
        language:  'en',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		minView: 2,
		forceParse: 0
    });
	$('.to').datetimepicker({
        language:  'en',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		minView: 2,
		forceParse: 0
    });
    $(function() {
		var dates = $( "#from, #to" ).datepicker({
			defaultDate:'',
			changeMonth: true,
			numberOfMonths: 1,
			onSelect: function( selectedDate ) {
			var now =Date();
				var option = this.id == "from" ? "minDate" : "maxDate",
					instance = $(this).data("datepicker"),
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
			}
		});
	});
</script>

<script type="text/javascript">
//in this line of code, to display the datetimepicker,  we used ‘form_datetime’ as an argument to be
//passed in javascript. This is for Date and Time.

//this is for Date only
 	$('.form_date').datetimepicker({
        language:  'en',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		minView: 2,
		forceParse: 0
    });
</script>
        <script>


		  function checkall(selector)
		  {
		    if(document.getElementById('chkall').checked==true)
		    {
		      var chkelement=document.getElementsByName(selector);
		      for(var i=0;i<chkelement.length;i++)
		      {
		        chkelement.item(i).checked=true;
		      }
		    }
		    else
		    {
		      var chkelement=document.getElementsByName(selector);
		      for(var i=0;i<chkelement.length;i++)
		      {
		        chkelement.item(i).checked=false;
		      }
		    }
		  }

		  function checkNumber(textBox)
			{
				while (textBox.value.length > 0 && isNaN(textBox.value)) {
					textBox.value = textBox.value.substring(0, textBox.value.length - 1)
				}
				textBox.value = trim(textBox.value);
			}
			//
			function checkText(textBox)
			{
				var alphaExp = /^[a-zA-Z]+$/;
				while (textBox.value.length > 0 && !textBox.value.match(alphaExp)) {
					textBox.value = textBox.value.substring(0, textBox.value.length - 1)
				}
				textBox.value = trim(textBox.value);
			}
			function validateBook(){
				var j=document.forms["book"]["adults"].value;
				if (j==null || j=="")
				  {
				 alert("select from adults");
				  return false;
				  }
				var k=document.forms["book"]["child"].value;
				if (k==null || k=="")
				  {
				  alert("select from kids ");
				  return false;
				  }
			}
			function dateDiff($start, $end) {

			$start_ts = strtotime($start);

			$end_ts = strtotime($end);

			$diff = $end_ts - $start_ts;

			return round($diff / 86400);

			}
		  </script>
		   <script language="javascript" type="text/javascript">
		        /* Visit http://www.yaldex.com/ for full source code
		and get more free JavaScript, CSS and DHTML scripts! */
		        <!-- Begin
		        var timerID = null;
		        var timerRunning = false;
		        function stopclock (){
		            if(timerRunning)
		                clearTimeout(timerID);
		            timerRunning = false;
		        }
		        function showtime () {
		            var now = new Date();
		            var hours = now.getHours();
		            var minutes = now.getMinutes();
		            var seconds = now.getSeconds()
		            var timeValue = "" + ((hours >12) ? hours -12 :hours)
		            if (timeValue == "0") timeValue = 12;
		            timeValue += ((minutes < 10) ? ":0" : ":") + minutes
		            timeValue += ((seconds < 10) ? ":0" : ":") + seconds
		            timeValue += (hours >= 12) ? " P.M." : " A.M."
		            document.clock.face.value = timeValue;
		            timerID = setTimeout("showtime()",1000);
		            timerRunning = true;
		        }
		        function startclock() {
		            stopclock();
		            showtime();
		        }

		        window.onload=startclock;
		        // End -->
		        //Validates Personal Info
				function personalInfo(){
				var y=document.forms["personal"]["name"].value;
				var a=document.forms["personal"]["last"].value;
				var b=document.forms["personal"]["address"].value;
				var c=document.forms["personal"]["city"].value;
				var d=document.forms["personal"]["zip"].value;
				var e=document.forms["personal"]["country"].value;
				var f=document.forms["personal"]["email"].value;
				var g=document.forms["personal"]["cemail"].value;
				var x=document.forms["personal"]["phone"].value;
				var i=document.forms["personal"]["password"].value;
				var atpos=f.indexOf("@");
				var dotpos=f.lastIndexOf(".");
				if (atpos<1 || dotpos<atpos+2 || dotpos+2>=f.length)
				  {
				  alert("Not a valid e-mail address");
				  return false;
				  }
				if( f != g ) {
				alert("email does not match");
				  return false;
				}
				if ((a=="Lastname" || a=="") || (b=="Address" || b=="") || (c=="City" || c=="") || (d=="ZIP Code" || d=="") || (e=="Country" || e=="") || (f=="Email" || f=="") || (g=="Confirm Email" || g=="")|| (x=="Contact Number" || x=="") || (y=="Firstname" || y=="") || (i=="Password" || i==""))
				  {
				  alert("all field are required!");
				  return false;
				  }

				if (document.personal.condition.checked == false)
				{
				alert ('pls. agree the term and condition of this hotel');
				return false;
				}
				else
				{
				return true;
				}
				}
		    </SCRIPT>
      </footer>
</div>
<!--/.container-->
</body>
</html>

joseadmin/templates/base-admin.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://bootswatch.com/yeti/bootstrap.css"/>
    {% block cssdmin %}

    {% endblock %}

</head>
<body>
<!-- nav start -->
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li ><a href="{% url 'administrador:reservaciones' %}">Reservaciones <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'administrador:paquetes' %}">Paquetes</a></li>
          <li><a href="{% url 'administrador:clientes' %}">Clientes</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
    </div>
  </div>
</nav>
<!-- nav end -->
<div class="col-md-12">
    <div class="container">
        {% block contenidoadmin %}
        {% endblock %}
    </div>
</div>

{% block jsadmin %}

{% endblock %}
</body>
</html>

joseadmin/templates/paquete-admin.html
{% extends "base-admin.html" %}
{% load staticfiles %}
{% block cssdmin %}

{% endblock %}
{% block contenidoadmin %}
 <div class="table-responsive">
    <table class="table" id="example">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Personas</th>
            <th>Sillas</th>
            <th>Cubresillas</th>
            <th>Mesas</th>
            <th>Manteles</th>
            <th>Cubremanteles</th>
            <th>Juego de Loza</th>
            <th>Precio</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
        </thead>
        <tbody>
            {% for foo in object_list %}
                <tr>
                    <td>{{ foo.nombre }}</td>
                    <td>{{ foo.personas }}</td>
                    <td>{{ foo.sillas }}</td>
                    <td>{{ foo.cubresillas }}</td>
                    <td>{{ foo.mesas }}</td>
                    <td>{{ foo.manteles }}</td>
                    <td>{{ foo.cubremanteles }}</td>
                    <td>{{ foo.juego_loza }}</td>
                    <td><strong>{{ foo.precio }}</strong></td>
                    <td><a href="{% url "administrador:paqueteEdit" foo.id %}">Editar</a></td>
                    <td><a href="{% url "administrador:paqueteDelete" foo.id %}">Eliminar</a></td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

 </div>
    <hr/>
    <a class="btn btn-primary" href="{% url "administrador:paqueteNew" %}">Crear Nuevo Paquete</a>




{% endblock %}
{% block jsadmin %}
    <script src="{% static "js/datatables.min.js" %}"></script>
        <script type="text/javascript">
	// For demo to fit into DataTables site builder...
	$('#example')
		.removeClass( 'display' )
		.addClass('table table-striped table-bordered');
</script>
        <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
{% endblock %}

joseadmin/templates/paquetes/actualizar_paquete.html
{% extends "base-admin.html" %}
{% block contenidoadmin %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <br/>
    <input type="submit" value="Enviar" class="btn btn-primary" />
</form>
    <hr/>
    <div class="row">
        <p> <a href="{% url "administrador:paquetes" %}" class="btn btn-danger" >Regresar</a></p>
    </div>
{% endblock %}

joseadmin/templates/paquetes/crear_paquete.html
{% extends "base-admin.html" %}
{% block contenidoadmin %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

joseadmin/templates/reservaciones-admin.html
{% extends "base-admin.html" %}
{% load staticfiles %}
{% block cssdmin %}

{% endblock %}
{% block contenidoadmin %}
 <div class="table-responsive">
    <table class="table" id="example">
        <thead>
        <tr>
            <th>Cliente</th>
            <th>Paquete</th>
            <th>Fecha de reservacion</th>
            <th>fecha de reservacion prouesta</th>
            <th>Confirmación</th>
            <th>Confirmar reservación</th>
        </tr>
        </thead>
        <tbody>
            {% for foo in object_list %}
                <tr>
                    <td>{{ foo.cliente }}  {{ foo.cliente.apellidos }}</td>
                    <td>{{ foo.paquete }}</td>
                    <td>{{ foo.fecha_ahora }}</td>
                    <td>{{ foo.fecha }}</td>
                    {% if foo.confirmacion == True %}
                          <td class="alert alert-success" >Si</td>
                    {% else %}
                        <td class="alert alert-danger" >No</td>
                    {% endif %}

                    <td><a href="{% url "administrador:reservacionEdit" foo.id %}">Editar</a></td>
                </tr>
            {% endfor %}
                
        </tbody>
    </table>
 </div>




{% endblock %}
{% block jsadmin %}
    <script src="{% static "js/datatables.min.js" %}"></script>
        <script type="text/javascript">
	// For demo to fit into DataTables site builder...
	$('#example')
		.removeClass( 'display' )
		.addClass('table table-striped table-bordered');
</script>
        <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
{% endblock %}